import 'package:flutter/material.dart';

///This file is automatically generated.
/// DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const rateStar = "assets/icons/star22.png";
  static const closeSquare = "assets/icons/close-square.png";
  static const emojiHappy = "assets/icons/emoji-happy.png";
  static const tickSquare = "assets/icons/tick-square.png";
  static const arrowRight = "assets/icons/arrow_right.png";
}

extension AssetsHelper on String {
  Image get png => Image.asset(this);
}
